<h3><?php echo __('Google Fonts', 'sumedia-gfont'); ?> <small><?php echo SUMEDIA_GFONT_VERSION; ?></small></h3>
<small>sumedia-gfont</small>
<div class="sumedia-overview-plugin">
    <div class="sumedia-overview-plugin-description">
        <p>
            <?php
                echo __('This Plugin provide a selection of Googles Font Library with Open Font licenced fonts.','sumedia-gfont');
            ?>
        </p>
    </div>
    <div class="sumedia-overview-plugin-actions">
        <p>
            <a href="<?php echo admin_url('admin.php?page=sumedia&plugin=gfont'); ?>"><?php echo __('Configuration', 'sumedia-gfont'); ?></a>
        </p>
    </div>
</div>
