<?php

if (!defined('SUMEDIA_BASE_VERSION')) {
    header( 'Status: 403 Forbidden' );
    header( 'HTTP/1.1 403 Forbidden' );
    exit();
}

?>
<h3><?php echo __('Google Fonts', 'sumedia-gfont'); ?> <small><?php echo SUMEDIA_GFONT_VERSION; ?></small></h3>
<small>sumedia-gfont</small>
<div class="sumedia-overview-plugin">
    <div class="sumedia-overview-plugin-description">
        <p>
            <?php
                echo __('This plugin provide a selection of the Google Fonts Library with Open Font licenced fonts.','sumedia-gfont');
            ?>
        </p>
    </div>
    <div class="sumedia-overview-plugin-actions">
        <p>
            <a href="<?php echo admin_url('admin.php?page=sumedia&plugin=gfont'); ?>"><?php echo __('Configuration', 'sumedia-gfont'); ?></a>
        </p>
    </div>
</div>
